services:
  APPNAME:
    restart: unless-stopped 
    container_name: APPNAME 
    image: DOCKER/IMAGE:TAG 
    hostname: APPNAME 
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    networks: 
      - saltbox
    labels:
      com.github.saltbox.saltbox_managed: true 
      traefik.enable: true 
      traefik.http.routers.APPNAME-http.entrypoints: web 
      traefik.http.routers.APPNAME-http.middlewares: globalHeaders@file,redirect-to-https@docker,robotHeaders@file,cloudflarewarp@docker,authelia@docker 
      traefik.http.routers.APPNAME-http.rule: Host(`APPNAME.yourdomain.com`) 
      traefik.http.routers.APPNAME-http.service: APPNAME 
      traefik.http.routers.APPNAME.entrypoints: websecure 
      traefik.http.routers.APPNAME.middlewares: globalHeaders@file,secureHeaders@file,robotHeaders@file,cloudflarewarp@docker,authelia@docker 
      traefik.http.routers.APPNAME.rule: Host(`APPNAME.yourdomain.com`) 
      traefik.http.routers.APPNAME.service: APPNAME 
      traefik.http.routers.APPNAME.tls.certresolver: cfdns 
      traefik.http.routers.APPNAME.tls.options: securetls@file 
      traefik.http.services.APPNAME.loadbalancer.server.port: APPLICATION_PORT 
    volumes: 
      - /opt/APPNAME:/CONFIG
      - /etc/localtime:/etc/localtime:ro

networks: 
  saltbox:
    external: true