sudo apt-get update
sb update
sb install saltbox
sb install sandbox

sb install gluetun
sb install qbittorrent
sb install sandbox-adminer
sb install sandbox-alltube
sb install asshama
sb install sandbox-audiobookshelf
sb install bazarr
sb install sandbox-code-server
sb install sandbox-filebrowser
sb install sandbox-flaresolverr
sb install sandbox-glances-web
sb install grafana
sb install sandbox-handbrake
sb install sandbox-homepage
sb install sandbox-influxdb
sb install jellyfin
sb install sandbox-jellyseerr
sb install sandbox-kavita
sb install lidarr
sb install sandbox-logarr
sb install sandbox-makemkv
sb install netdata
sb install nzbget
sb install nzbhydra2
sb install organizr
sb install overseerr
sb install plex
sb install sandbox-plex-meta-manager
sb install sandbox-plextraktsync
sb install sandbox-plex-utills
sb install postgres
sb install sandbox-privatebin
sb install prowlarr
sb install radarr
sb install sandbox-recyclarr
sb install sandbox-redis
sb install sandbox-requestrr
sb install sandbox-resiliosync
sb install rutorrent
sb install sabnzbd
sb install sonarr
sb install sandbox-speedtest
#sb install sandbox-stash
sb install tautulli
sb install sandbox-telegraf
sb install traefik
sb install sandbox-unpackerr
sb install sandbox-uptime
sb install sandbox-varken
sb install sandbox-vaultwarden
sb install sandbox-vnstat
sb install sandbox-whisparr
sb install sandbox-wireguard
sb install sandbox-wizarr
sb install sandbox-xteve
sb install hetzner-nfs-client-mount

sudo reboot
